<label for="title">Title</label>
<input type="text" class="form-control" name="title" placeholder="Product title" value="{{ $product->title or "" }}" required>

<label for="slug">Slug</label>
<input type="text" class="form-control" name="slug" placeholder="Autogenerated" value="{{ $product->slug or "" }}" readonly="">

<label for="status">Status</label>
<select name="status" class="form-control">

  @if (isset($product->id))
    
    <option value="0" @if (0 == $product->published) selected="" @endif> Draft</option>
    <option value="1" @if (1 == $product->published) selected="" @endif> Published</option>
  @else
      
    <option value="0"> Draft</option>
    <option value="1"> Published</option>
  @endif
</select>

<label for="price">Price</label>
<input type="number" pattern="[0-9]+([\.,][0-9]+)?" step="0.01" class="form-control" name="price" placeholder="1.00" value="{{ $product->price or "" }}" required>

<label for="description">Description</label>
<textarea name="description" class="form-control" cols="30" rows="10" required>{{ $product->description or "" }}</textarea>

<br>

<input class="btn btn-primary" type="submit" value="Save">