
<label for="id">Telegram id</label>
<input type="text" class="form-control" name="id" placeholder="Autogenerated" value="{{ $teluser->id or "" }}" readonly="">

<label for="is_bot">Is bot</label>
<select name="is_bot" class="form-control">

  @if (isset($teluser->id))
    
    <option value="0" @if (0 == $teluser->is_bot) selected="" @endif> No</option>
    <option value="1" @if (1 == $teluser->is_bot) selected="" @endif> Yes</option>
  @else
      
    <option value="0"> No</option>
    <option value="1"> Yes</option>
  @endif
</select>

<label for="first_name">First name</label>
<input type="text" class="form-control" name="first_name" placeholder="First name" value="{{ $teluser->first_name or "" }}">

<label for="last_name">Last name</label>
<input type="text" class="form-control" name="last_name" placeholder="Last name" value="{{ $teluser->last_name or "" }}">

<label for="username">Username</label>
<input type="text" class="form-control" name="username" placeholder="Username" value="{{ $teluser->username or "" }}">

<label for="id">Subsribe date</label>
<input type="text" class="form-control" name="id" value="{{ $teluser->subscribe_date or "" }}" readonly="">

<br>

<input class="btn btn-primary" type="submit" value="Save">